-- QuietAlpha 봇 랭킹 / 거래내역
-- Database: DEMO_RAW_DB  Schema: RAW
-- 샘플 데이터는 bot_seed.sql 을 한 번만 실행하세요. 앱 기동 시 자동 insert 하지 않습니다.

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.BOT (
    BOT_ID          NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    BOT_CODE        VARCHAR(100) NOT NULL UNIQUE,
    BOT_NAME        VARCHAR(200) NOT NULL,
    DESCRIPTION     VARCHAR(500),
    MODEL_TYPE      VARCHAR(50),
    STRATEGY_TYPE   VARCHAR(100),
    PAPER_TRADING   CHAR(1) DEFAULT 'Y',
    IS_ACTIVE       CHAR(1) DEFAULT 'Y',
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.BOT_PERF_DAILY (
    BOT_ID          NUMBER NOT NULL,
    PERF_DATE       DATE NOT NULL,
    DAILY_RETURN    FLOAT,
    CUM_RETURN      FLOAT,
    PRIMARY KEY (BOT_ID, PERF_DATE)
);

CREATE TABLE IF NOT EXISTS DEMO_RAW_DB.RAW.BOT_TRADE (
    TRADE_ID        NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    BOT_ID          NUMBER NOT NULL,
    SYMBOL          VARCHAR(100) NOT NULL,
    SYMBOL_NAME     VARCHAR(200),
    SELECT_REASON   VARCHAR(1000),
    BUY_PRICE       NUMBER(18, 4),
    BUY_AT          TIMESTAMP_NTZ NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
